blog_homepage:
    path:     /
    defaults: { _controller: BlogBundle:Default:index }

blog_post_view:
    path:     /post/{id}
    defaults: { _controller: BlogBundle:Post:view }
    requirements:
        id: \d+

blog_post_add:
    path:     /post/add
    defaults: { _controller: BlogBundle:Post:add }

blog_post_edit:
    path:     /post/{id}/edit
    defaults: { _controller: BlogBundle:Post:edit }
    requirements:
        id: \d+

blog_post_delete:
    path:     /post/{id}/delete
    defaults: { _controller: BlogBundle:Post:delete }
    requirements:
        id: \d+

