user:
    resource: "@UserBundle/Resources/config/routing.yml"
    prefix:   /Rezo/user/

core:
    resource: "@CoreBundle/Resources/config/routing.yml"
    prefix:   /Rezo/

blog:
    resource: "@BlogBundle/Resources/config/routing.yml"
    prefix:   /Rezo/blog/

app:
    resource: "@AppBundle/Controller/"
    type:     annotation

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
    prefix: /Rezo/user/
