core:
    resource: "@CoreBundle/Resources/config/routing.yml"
    prefix:   /Rezo/

blog:
    resource: "@BlogBundle/Resources/config/routing.yml"
    prefix:   /Rezo/blog/

app:
    resource: "@AppBundle/Controller/"
    type:     annotation
