admin:
    resource: "@AdminBundle/Resources/config/routing.yml"
    prefix:   /admin/

user:
    resource: "@UserBundle/Resources/config/routing.yml"
    prefix:   /user/

core:
    resource: "@CoreBundle/Resources/config/routing.yml"
    prefix:   /

blog:
    resource: "@BlogBundle/Resources/config/routing.yml"
    prefix:   /blog/

app:
    resource: "@AppBundle/Controller/"
    type:     annotation

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
    prefix: /

fos_user_group:
    resource: "@FOSUserBundle/Resources/config/routing/group.xml"
    prefix: /group