admin_homepage:
    path:     /
    defaults: { _controller: AdminBundle:Default:index }

admin_dashboard:
    path: /dashboard/
    defaults: { _controller: AdminBundle:Default:dashboard }

admin_menuitem:
    path: /menuitem/
    defaults: { _controller: AdminBundle:MenuItem:index }

# ... Admin Blog
admin_blog_post:
    path:     /blog/post
    defaults: { _controller: AdminBundle:AdminPost:index }

admin_blog_post_findAll:
    path: /blog/post/findall
    defaults: { _controller: AdminBundle:AdminPost:findAll }
    requirements:
        methods: POST