admin_homepage:
    path:     /
    defaults: { _controller: AdminBundle:Default:index }

admin_dashboard:
    path: /dashboard/
    defaults: { _controller: AdminBundle:Default:dashboard }

admin_menuitem:
    path: /menuitem/
    defaults: { _controller: AdminBundle:MenuItem:index }

# ... Admin Blog
admin_blog_post:
    path:     /blog/post
    defaults: { _controller: AdminBundle:AdminPost:index }

admin_blog_post_edit:
    path: /blog/post/{id}/edit
    defaults: { _controller: AdminBundle:AdminPost:edit }
    requirements:
        id: \d+
        methods: POST
    options:
        expose: true

admin_blog_post_load:
    path: /blog/post/load
    defaults: { _controller: AdminBundle:AdminPost:load }
    requirements:
        methods: POST