parameters:
    # ...
    admin_bundle.menu_listener.class: Rezo\Bundle\AdminBundle\EventListener\MenuItemListListener

services:
    # ...
    admin_bundle.menu_listener:
        class: %admin_bundle.menu_listener.class%
        tags:
            - { name: kernel.event_listener, event: theme.sidebar_setup_menu, method: onSetupMenu }
